# This file is a template, and might need editing before it works on your project.
docker-build-dev:
  # Official docker image .
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  variables:
    # Tell docker CLI how to talk to Docker daemon; see
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
    DOCKER_HOST: tcp://docker:2375/
    # Use the overlayfs driver for improved performance:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u ${ACCESS_USER} -p "${ACCESS_TOKEN}" registry.gitlab.com
  script:
    - docker build -t ${DOCKER_ENV_CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} --build-arg branch=${CI_COMMIT_REF_NAME} . -f ./Sarnado.PayGate/Dockerfile
    - docker push ${DOCKER_ENV_CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
